### ISSUE TITLE
Different FENs on online Live Demo and on Source code

### ISSUE THREAD

**Issue by rayoh123** [Elucidation/ChessboardScreenshotHtml5#10]
I am trying to find the FEN of https://i.redd.it/jafm8w43mzk31.jpg
I used the Live Demo of FENbot, and it gave me the correct FEN. However, when I do: 

**$ ./tensorflow_chessbot.py --url https://i.redd.it/jafm8w43mzk31.jpg**

I get the incorrect FEN. Why does this difference happen?

**Comment by Elucidation** [comment]
Hmm, I think I must've used a different frozen model for the javascript-based online one versus the python one, if you have experience with TF frozen models you can download the one from the live demo's repo and replace it in the python one to get the same results
