### ISSUE TITLE
Unable to identify the corner black pawn on black square

### ISSUE THREAD

**Issue by ssingh10** [Elucidation/ChessboardScreenshotHtml5#7]
![cb14-colored-arrows-01](https://user-images.githubusercontent.com/1434870/58673249-6ab48e80-82ff-11e9-954d-9bdc2f022be6.jpg)

**Comment by Elucidation** [comment]
Fixed with c5007ca , errors in bounding box / texture handled better with box filter
![image](https://github.com/Elucidation/ChessboardFenTensorflowJs/assets/434925/d2dc02f3-7c6b-4ed5-af7d-a1dc74f5e54d)
